### ISSUE TITLE
Submitting another awesome list

### ISSUE THREAD

**Issue by Leamsi9** [Green-Software-Foundation/awesome-green-software#103]
Hello, the Adora Foundation has been curating an [awesome green extensions](https://github.com/Adora-Foundation/awesome-green-extensions) list. Each of the entries is relevant to this list, and as far as I can see not included here. There doesn't seem to be a category for collections of resources. I thought of maybe just copying our list and creating a section and pushing, but the data format in our repo is much more detailed and doesn't fit with this repo. We might have time to add our work to the repo one by one at some point (should we add a browser extensions category, or just add each extension under #web?), but can't guarantee consistency as we keep updating our repo, so linking to the repo itself would make more sense to have access to the latest version. Any suggestions?

**Comment by prof-antar** [comment]
Thanks @Leamsi9 for the suggestion. We are in the process of reviewing the whole project as we're in the process of consolidating multiple lists together. Your suggestion fits well into that exercise. I will incorporate it into the revamped copy.

**Comment by prof-antar** [comment]
added the active and relevant ones.
