### ISSUE TITLE
Article no longer exists under link provided 

### ISSUE THREAD

**Issue by sasha-cz** [Green-Software-Foundation/awesome-green-software#146]
@dtoakley-tw I just saw that one of the links below 'Articles'  in Readme.md is leading to a 404 Error page.
 
Steps to reproduce:

1. Open Readme.md.
2. Scroll down to Articles and click on the first Link 'Assessing the suitability of the Greenhouse Gas Protocol for calculation of emissions from public cloud computing workloads'.
Expected result: User gets access to the article of David Mytton.  
Actual result: A 404 Error is displayed.

I found the article (from 2020) alternatively here for Download: 
https://journalofcloudcomputing.springeropen.com/articles/10.1186/s13677-020-00185-8

Can I fix this?

**Comment by prof-antar** [comment]
This URL has been fixed. Verified it is working. Hence, closing the issue. Thanks again for your feedback.
