### ISSUE TITLE
Could we add the `awesome` topic to this repo?

### ISSUE THREAD

**Issue by sampart** [Green-Software-Foundation/awesome-green-software#147]
This repo is already tagged with the [`awesome-list` topic](https://github.com/topics/awesome-list), but the [`awesome` topic](https://github.com/topics/awesome) seems pretty relevant too.

**Comment by sampart** [comment]
Plus `awesome` is the topic linked to from https://github.com/sindresorhus/awesome#related

**Comment by prof-antar** [comment]
Hi @sampart , thanks for the suggestion. added.
