### ISSUE TITLE
"awesome list" link error

### ISSUE THREAD

**Issue by MarcePSS** [Green-Software-Foundation/awesome-green-software#151]
Hi, the "awesome list" link in the introduction is pointing to another unrelated list.
Specifically, it is linking to https://github.com/sindresorhus/awesome#readme.

**Comment by isabeladematos** [comment]
Hello @MarcePSS,

Appreciate you spotting that! The link to sindresorhus' awesome list is intentional, serving as a reference for inspiration.
If you have any questions or concerns, please feel free to let me know.

Cheers,

**Comment by isabeladematos** [comment]
Hello @MarcePSS,

Appreciate you spotting that! 
I think the link to sindresorhus' awesome list is intentional, serving as a reference for inspiration.

Cheers,
