### ISSUE TITLE
The python package energyusage is no longer actively maintaining

### ISSUE THREAD

**Issue by bsab** [Green-Software-Foundation/awesome-green-software#51]
As reported on the [official github page](https://github.com/responsibleproblemsolving/energy-usage
), the python package **energyusage** is no longer actively maintaining because it has merged into [CodeCarbon ](https://codecarbon.io/)project.

**Comment by dtoakley** [comment]
Sorry for the delay, but good catch @bsab -- would you be able to create a PR to remove energyusage from the list, pointing to the `dev` branch? No worries if not though - I can do it in that case.

**Comment by bsab** [comment]
@dtoakley I've create a PR pointing to **dev** branch but it has conflicts that must be resolved.

**Comment by dtoakley-tw** [comment]
Closing this out because it should have been closed out when we made the last release! Thanks again @bsab
