### ISSUE TITLE
The link to the Azure Microsoft Sustainability Calculator returns a 404 Error page

### ISSUE THREAD

**Issue by bsab** [Green-Software-Foundation/awesome-green-software#52]
The link to the **Azure Microsoft Sustainability Calculator** returns a **404 Error page.**
This is the [broken link](https://appsource.microsoft.com/en-us/product/power-bi/coi-sustainability.sustainability_dashboard).

Maybe you should refer to this [link](https://www.microsoft.com/en-us/sustainability/emissions-impact-dashboard).

**Comment by dtoakley** [comment]
Good catch @bsab -- I've pushed a fix for the dev branch, so will be updated when we merge it to main. Thank you!
