### ISSUE TITLE
The link to Carbonalyser - TheShiftProject returns 404 Error page

### ISSUE THREAD

**Issue by bsab** [Green-Software-Foundation/awesome-green-software#53]
The link to the **Carbonalyser - TheShiftProject**  returns a 404 Error page.
This is the broken [link](https://chrome.google.com/webstore/detail/carbonalyser/oblfkaonopplpldppkjdhnlcmkhgbcok).

Maybe you should refer to this [link](https://theshiftproject.org/en/carbonalyser-browser-extension/).

**Comment by dtoakley** [comment]
Good catch @bsab -- I've pushed a fix for the dev branch, so will be updated when we merge it to main. Thank you!

**Comment by dtoakley-tw** [comment]
Closing this out as it should have been closed after the last release. Fix is on main.
