### ISSUE TITLE
2 Android-specific tools

### ISSUE THREAD

**Issue by olegoaer** [Green-Software-Foundation/awesome-green-software#61]
Hello guys and @dtoakley,

I am currently working on 2 open source projects that may interest you:

- [ecoCode](https://github.com/cnumr/ecoCode/tree/main/sonarqube-plugin-greenit/native-analyzer/android-plugin) : a sonarQube plugin dedicated to green code analysis of android projects
- [powDroid](https://git.univ-pau.fr/powdroid/powdroid): a lightweight tool for measuring the energy footprint of any android application

Both are still in the prototype stage but development is progressing well. I've already done demos.

Regards,

**Comment by dtoakley** [comment]
Hi @olegoaer -- thanks so much for submitting this issue. Apologies for the delay. 

Would you be open to creating a PR pointing the `dev` branching to add these to the list? It can be in it's new sub-category under tools > OS-based > Android? If not, I can also do so!

**Comment by dtoakley-tw** [comment]
Closing this as it should have been closed after the last release. Updates are on main. thanks again @olegoaer
