### ISSUE TITLE
A Recommended Book List for Green Software

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/awesome-green-software#62]
Some books I've read
- [Designing for Sustainability by Tim Frick](https://www.amazon.co.uk/Designing-Sustainability-Tim-Frick/dp/1491935774)
- [Sustainable Web Design Book by Tom Greenwood](https://www.goodreads.com/en/book/show/56861271-sustainable-web-design)

Some books I've heard about: 
- [101 Green Software - A Practical Guide for Developers & Architects](https://leanpub.com/green-software/)

**Comment by dtoakley-tw** [comment]
I'm not sure how I missed this Issue, but apologies @jawache . I've pushed the first two books to the `dev` branch, and we have another contributor with a PR open for the third one, so I'll let them get that merge-able. All three will be in the next release though!
