### ISSUE TITLE
Tool Carbon Tracker mentioned 3 times on awesome-green-software page

### ISSUE THREAD

**Issue by memsyn** [Green-Software-Foundation/awesome-green-software#65]
- Twice mentioned under topic AI->Energy: https://github.com/Green-Software-Foundation/awesome-green-software#energy
1. [carbontracker](https://github.com/lfwa/carbontracker)
2. [Tool for tracking and predicting the energy consumption and carbon footprint of training deep learning models as described in Anthony et al. (2020)](https://arxiv.org/abs/2007.03051)

- Once mentioned under topic Codebased: https://github.com/Green-Software-Foundation/awesome-green-software#code-based
3. [carbontracker](https://github.com/lfwa/carbontracker)

Q: Was it intentionally been mentioned for 3 times? I found it a bit confusing when reviewing the tools.

**Comment by dtoakley** [comment]
Hi @memsyn -- thanks for submitting this issue and noticing the duplication. Our latest updates in the dev branch PR which you can see [here](https://github.com/Green-Software-Foundation/awesome-green-software/pull/50) remove this duplication. 

Once we merge those updates, this should be resolved.

**Comment by dtoakley-tw** [comment]
Closing this as it should have been closed after the last release. Updates are on main. thanks again @memsyn
