### ISSUE TITLE
Additional Organization: Green Software Design Community

### ISSUE THREAD

**Issue by ElmarBorgmeier** [Green-Software-Foundation/awesome-green-software#69]
Hi everyone,

I'm usually involved in the standards WG, but today I have a suggestion / request for this project:

The list of organizations does currently not include the _Green Software Design Community_ , https://www.GreenSoftwareDesign.com . 
The community has started in Germany, but is meant to grow to Europe (and yes, I know, that requires an english version of the website ...)
The focus is to bring companies together to work on green software, its application in the corporate context, and the inclusion of "digital green", meaning the impact of using the software.

I suggest adding this community to the list.

**Comment by dtoakley** [comment]
Thanks @ElmarBorgmeier -- and sorry for the delayed reply. This is a great suggestion -- would you be able to create a Pull Request with this addition, pointing to the `dev` branch? I can make sure it's included in the next release of the list.

**Comment by dtoakley-tw** [comment]
Closing this as it should have been closed after the last release. Updates are on main. thanks again @ElmarBorgmeier
