### ISSUE TITLE
Additional Organization: Roll The Cloud Inc.

### ISSUE THREAD

**Issue by ng-druid** [Green-Software-Foundation/awesome-green-software#77]
Hello,

I would like to make you aware of the non-profit which I'm the founder.

Roll the Cloud is dedicated to building the web back better to save our planet. Combat technology harmful to the the climate using alternative environmentally cautious software solutions. Being an active technical evangelist spearheading the greener web.

Missions:

* Reduce global energy consumption by producing energy efficient alternatives to popular apps and websites.
* Educate and inspire others to make climate conscious decisions when solving web development problems.
* Persuade community to use websites and apps that protect the environment.

Organization Page: https://github.com/rollthecloudinc
Website: https://rollthecloud.com/index (WIP)

Thanks

![rtc_full_color](https://user-images.githubusercontent.com/73197190/167282881-071bb023-30e7-40df-aaaa-081c0bf39933.png)

**Comment by dtoakley-tw** [comment]
Hi @ng-druid -- so sorry for missing this Issue. This sounds good -- would you be able to create a Pull Request pointing to the `dev` branch with this under the "Organizations" section? Let me know if that sounds okay to you!
