### ISSUE TITLE
Globemallow

### ISSUE THREAD

**Issue by con-schy1** [Green-Software-Foundation/awesome-green-software#89]
Hello,

I'd like to suggest 2 new tools under the Web category. 

[Globemallow.io ](https://globemallow.io/) has created 2 tools to help with a more sustainable internet.

1) Globemallow is a browser extensions that provides sustainable development and design reports for each webpage that you visit. Helping developers and designs create for a more sustainable web.

2) Analytics & Ad Blocker is a powerful extension that blocks trackers and advertisements while you browser the internet. Blocking all unnecessary code from running, and in many cases making websites load in half the time.

These tools do all this without tracking any of your data :) 

Disclaimer- I am the creator of both tools and the founder of Globemallow.

**Comment by Leamsi9** [comment]
Hey, 

I haven't used the analytics blocker, I use a different one, but I do use and like Globemallow. Would encourage you to open source it for greater visibility and usage, specially as the JS is already available on the browser.

Good work. Definitely would be good to add it to the list!

**Comment by con-schy1** [comment]
Thank you! I've definitely considered Open Sourcing it, and can see myself doing it in the near future. Right now, I'm having a lot of fun with it though :)

Check out A&A Blocker, it's pretty cool (if I do say so myself). 

Any feedback you have for Globemallow, please feel free to reach out. I'd love to hear it! 

Thanks and cheers!

**Comment by dtoakley-tw** [comment]
Thanks so much @con-schy1  -- apologies for the delay. Would you be able to create a pull request pointing to the `dev` branch with this added in the "Web" section? It's up to you, but I'm thinking maybe just one entry for both tools given there is one URL? Let me know what you think!

**Comment by con-schy1** [comment]
@dtoakley-tw Done :) Thanks.
