### ISSUE TITLE
contributing.md links off to the possibly incorrect site with unclarrified acronym

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/awesome-green-software#99]
When contributing found some issues in the contribution guide in dev... 

1. The 'title-casing' link links off to the "http://titlecapitalization.com/" website which I'm assuming is incorrect.  I'm not sure where this is meant to link to.

Image below.
![image](https://user-images.githubusercontent.com/252951/196817084-bdeb2360-1f2c-400e-9ec9-a5323d6889cd.png)

2. The link also has a clarification `(AP Style)` but with an assumed definition of the acronym.  I'm not sure what this means.

@dtoakley - was the bit you added 22 days ago so you might be able to help out :)

**Comment by dtoakley-tw** [comment]
Thanks @vaughanknight -- I've fixed this in the dev branch. Good catch.

**Comment by dtoakley-tw** [comment]
Merged to main. Closing this issue!
